version: "3"
services:
  react:
    build: ./react
    container_name: react_container
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - random-number-app
    volumes:
      - ./react:/app
      - /app/node_modules

  nodejs_service:
    build: ./nodejs_service
    container_name: nodejs_service_container2
    ports:
      - "6004:6004"
    networks:
      - random-number-app
    volumes:
      - ./nodejs_service:/app
      - /app/node_modules
      
networks:
  random-number-app:
    driver: bridge
